### ISSUE TITLE
Can't connect to mysql on 127.0.0.1

### ISSUE THREAD

**Issue by fadehelix** [FoodCoopSystem/docker#4]
By default drupal is trying to connect with mysql server by using 127.0.0.1 address. I was even trying to connect from foodcoop_web contaiiner and it's been working only after change host from 127.0.0.1 to link name "db".
Then I changed drupal settings.php to use "db" as host and it's working.

**Comment by jsobiecki** [comment]
Ok, thanks for info. I'll add additional section to documentation, that will describe steps as above.
